services:
  pay_checker_api:
    container_name: pay_checker_api
    restart: always
    env_file: .env
    build:
        context: .
    ports:
      - 6845:8080
    healthcheck:
      test: curl --fail http://localhost:8080 || exit 1
      interval: 2m30s
      timeout: 30s
      retries: 5
      start_period: 30s